import { Product, Collection } from '@/types';

export const mockProducts: Product[] = [
  {
    id: '1',
    slug: 'robe-aurore',
    status: 'active',
    category: 'dresses',
    name_fr: 'Robe Aurore',
    name_en: 'Aurora Dress',
    description_fr: 'Une robe majestueuse en soie sauvage, drapée comme un lever de soleil sur la peau. Chaque couture raconte une promesse de renaissance.',
    description_en: 'A majestic wild silk dress, draped like a sunrise on the skin. Every stitch tells a promise of rebirth.',
    story_fr: 'Aurore est née d\'une aube observée à Douala, quand la lumière rose et or a embrassé l\'horizon. Cette pièce capture cet instant suspendu — cette seconde où tout devient possible.',
    story_en: 'Aurora was born from a dawn observed in Douala, when pink and gold light kissed the horizon. This piece captures that suspended moment — that second when everything becomes possible.',
    materials_fr: 'Soie sauvage, doublure en coton organique',
    materials_en: 'Wild silk, organic cotton lining',
    care_fr: 'Nettoyage à sec recommandé. Repasser à basse température.',
    care_en: 'Dry cleaning recommended. Iron on low heat.',
    base_price_eur: 89000,
    price_overrides: { USD: 96000, GBP: 76000, CAD: 130000 },
    made_to_order: true,
    made_to_order_min_days: 14,
    made_to_order_max_days: 21,
    made_to_measure: false,
    preorder: false,
    images: ['/placeholder.svg'],
    sizes: ['34', '36', '38', '40', '42', '44'],
    colors: ['Noir Profond', 'Ivoire', 'Magenta'],
    materials: ['Soie sauvage'],
    braiding_options: ['Tressage Soleil', 'Tressage Lune'],
    stock_qty: null,
    editorial_blocks_json: null,
  },
  {
    id: '2',
    slug: 'ensemble-eclipse',
    status: 'active',
    category: 'sets',
    name_fr: 'Ensemble Éclipse',
    name_en: 'Eclipse Set',
    description_fr: 'Un ensemble deux pièces en lin noble. Le haut structuré et la jupe fluide créent un jeu d\'ombre et de lumière sur la silhouette.',
    description_en: 'A two-piece set in noble linen. The structured top and flowing skirt create a play of shadow and light on the silhouette.',
    story_fr: 'L\'Éclipse symbolise ce moment où l\'on accepte ses parts d\'ombre pour mieux révéler sa lumière intérieure. Porter cet ensemble, c\'est embrasser sa dualité.',
    story_en: 'The Eclipse symbolizes that moment when we accept our shadows to better reveal our inner light. Wearing this set means embracing one\'s duality.',
    materials_fr: 'Lin européen, finitions en soie',
    materials_en: 'European linen, silk finishes',
    care_fr: 'Lavage délicat à 30°C. Séchage à plat.',
    care_en: 'Gentle wash at 30°C. Flat drying.',
    base_price_eur: 72000,
    price_overrides: { USD: 78000, GBP: 62000, CAD: 105000 },
    made_to_order: true,
    made_to_order_min_days: 10,
    made_to_order_max_days: 18,
    made_to_measure: true,
    preorder: false,
    images: ['/placeholder.svg'],
    sizes: ['34', '36', '38', '40', '42'],
    colors: ['Noir', 'Blanc Cassé'],
    materials: ['Lin européen'],
    braiding_options: ['Tressage Terre'],
    stock_qty: null,
    editorial_blocks_json: null,
  },
  {
    id: '3',
    slug: 'haut-solstice',
    status: 'active',
    category: 'tops',
    name_fr: 'Haut Solstice',
    name_en: 'Solstice Top',
    description_fr: 'Un haut en coton soyeux, orné d\'un tressage artisanal inspiré des traditions camerounaises. La rencontre de deux mondes dans un vêtement.',
    description_en: 'A silky cotton top adorned with artisanal braiding inspired by Cameroonian traditions. The meeting of two worlds in one garment.',
    story_fr: 'Solstice célèbre le point de bascule, ce jour le plus long où la lumière atteint son apogée. Ce haut est une ode à votre moment de plénitude.',
    story_en: 'Solstice celebrates the tipping point, that longest day when light reaches its peak. This top is an ode to your moment of fullness.',
    materials_fr: 'Coton pima, broderie artisanale',
    materials_en: 'Pima cotton, artisanal embroidery',
    care_fr: 'Lavage à la main recommandé.',
    care_en: 'Hand wash recommended.',
    base_price_eur: 38000,
    price_overrides: { USD: 41000, GBP: 33000, CAD: 56000 },
    made_to_order: false,
    made_to_measure: false,
    preorder: true,
    preorder_ship_date_estimate: '2026-04-15',
    images: ['/placeholder.svg'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    colors: ['Ivoire', 'Noir'],
    materials: ['Coton pima'],
    braiding_options: ['Tressage Héritage', 'Tressage Libre'],
    stock_qty: 12,
    editorial_blocks_json: null,
  },
];

export const mockCollections: Collection[] = [
  {
    id: '1',
    slug: 'renaissance',
    title_fr: 'Renaissance',
    title_en: 'Renaissance',
    subtitle_fr: 'Collection Printemps-Été 2026',
    subtitle_en: 'Spring-Summer 2026 Collection',
    narrative_fr: 'Renaissance est un chant, un souffle, une promesse. Cette collection est née d\'un désir profond de célébrer la femme dans sa transformation la plus intime. Chaque pièce a été pensée comme un chapitre d\'une histoire que seule vous pouvez écrire.\n\nDe Douala à Paris, du lin à la soie, chaque matière a été choisie pour sa capacité à épouser le corps et à libérer le mouvement. Les tressages artisanaux racontent un héritage transmis de main en main, de mère en fille, de continent en continent.\n\nPorter Renaissance, c\'est accepter de renaître chaque matin. C\'est choisir de s\'écrire soi-même.',
    narrative_en: 'Renaissance is a song, a breath, a promise. This collection was born from a deep desire to celebrate women in their most intimate transformation. Each piece was conceived as a chapter of a story that only you can write.\n\nFrom Douala to Paris, from linen to silk, each material was chosen for its ability to embrace the body and free movement. The artisanal braiding tells a heritage passed from hand to hand, from mother to daughter, from continent to continent.\n\nWearing Renaissance means accepting to be reborn every morning. It means choosing to write yourself.',
    cover_image: '/placeholder.svg',
    gallery_images: ['/placeholder.svg', '/placeholder.svg', '/placeholder.svg'],
    published_at: '2026-01-15',
    tags: ['printemps-été', 'renaissance', 'soie', 'lin'],
    product_ids: ['1', '2', '3'],
  },
];

export const faqData = {
  fr: [
    { q: 'Quels sont les délais de confection ?', a: 'Nos pièces sur commande sont confectionnées en 10 à 21 jours selon le modèle. Les pièces sur mesure peuvent nécessiter un délai supplémentaire.' },
    { q: 'Comment prendre mes mesures ?', a: 'Un guide détaillé de prise de mesures est disponible sur chaque page produit sur mesure. N\'hésitez pas à nous contacter pour une assistance personnalisée.' },
    { q: 'Quelles sont les options de livraison ?', a: 'Nous livrons en Europe, au Royaume-Uni, aux États-Unis et au Canada. Les frais et délais varient selon votre zone géographique.' },
    { q: 'Puis-je retourner une pièce sur mesure ?', a: 'Les pièces sur mesure ne sont pas retournables sauf en cas de défaut de fabrication. Les pièces en stock peuvent être retournées sous 14 jours.' },
    { q: 'Quels modes de paiement acceptez-vous ?', a: 'Nous acceptons les cartes bancaires (Visa, Mastercard, AMEX) via un paiement sécurisé Stripe, en EUR, USD, GBP et CAD.' },
    { q: 'Comment entretenir mes pièces ?', a: 'Chaque pièce est accompagnée de ses instructions d\'entretien spécifiques, visibles sur la fiche produit.' },
  ],
  en: [
    { q: 'What are the crafting lead times?', a: 'Our made-to-order pieces are crafted in 10 to 21 days depending on the design. Made-to-measure pieces may require additional time.' },
    { q: 'How do I take my measurements?', a: 'A detailed measurement guide is available on each made-to-measure product page. Feel free to contact us for personalized assistance.' },
    { q: 'What are the shipping options?', a: 'We ship to Europe, the UK, the US, and Canada. Fees and delivery times vary by region.' },
    { q: 'Can I return a made-to-measure piece?', a: 'Made-to-measure pieces are non-returnable unless there is a manufacturing defect. In-stock pieces can be returned within 14 days.' },
    { q: 'What payment methods do you accept?', a: 'We accept credit cards (Visa, Mastercard, AMEX) via secure Stripe payment, in EUR, USD, GBP, and CAD.' },
    { q: 'How do I care for my pieces?', a: 'Each piece comes with specific care instructions, visible on the product page.' },
  ],
};
